### ISSUE TITLE
Date picker popup not showing up correctly when screen size is small (on mobile)

### ISSUE THREAD

**Issue by ransa808** [awerlang/angular-responsive-tables#14]
Date picker pop up looks very weird when table is narrow (like on mobile devices).
Please see screenshot attached.

Any idea how to solve this issue ?

Thanks
![file 29-06-2016 14 08 30](https://cloud.githubusercontent.com/assets/7548070/16450076/aadb76ac-3e03-11e6-9d1e-ac853275cc3e.png)

**Comment by awerlang** [comment]
Can you provide a plunker?

**Comment by awerlang** [comment]
Popups often exhibit this kind of problem. Does this component provide an `attachToBody` configuration? It might solve this issue.

**Comment by ransa808** [comment]
tried datepicker-append-to-body=true  - seems like it's not really affecting something.
Will try to have a plunker tomorrow

**Comment by andycwwai** [comment]
![image](https://cloud.githubusercontent.com/assets/3676394/18630162/419b795a-7e9d-11e6-9c35-b760f596002e.png)

I have something more strange that the columns titles are showing in the popup datetime picker. Please suggest.

**Comment by awerlang** [comment]
This happens because the datepicker is a nested table, although the result is inconvenient.

Can you verify if this could solve your problem, if not already applied:

> Popups often exhibit this kind of problem. Does this component provide an attachToBody configuration? It might solve this issue.

Which datapicker component are you using?

**Comment by andycwwai** [comment]
I'm using this https://github.com/dalelotts/angular-bootstrap-datetimepicker
What we need is a popup datetime picker, not embedded in body. Is it because of injecting all the "td" with the title/cell recursively? I saw you have a change "tables without the directive are ignored". Is this done with the intention to solve this issue? You are doing a great work here and I really appreciate if such issue can be solved. Many thanks.

**Comment by awerlang** [comment]
The other commit handles a similar issue, but on a top-level table element. It doesn't handle this issue because the datepicker is a table nested inside a responsive table. I'll take a closer look at this.

**Comment by andycwwai** [comment]
Thanks.

**Comment by awerlang** [comment]
@andycwwai @ransalman Please, if possible, update to v0.4.0 and verify if issue is indeed resolved. Please re-open if necessary.

**Comment by andycwwai** [comment]
![image](https://cloud.githubusercontent.com/assets/3676394/18695229/f5e9a2c4-7fe2-11e6-90ad-f157f3e8d2d1.png)

The datetime picker calendar can be shown correctly but the text and title are overlapped.

**Comment by awerlang** [comment]
Can you provide a plunker?

**Comment by awerlang** [comment]
Actually I believe this is another issue not related to the date picker anymore, but emerged with the previous fix. To give more context, I made selectors more strict. This could be either a syntactical error on your markup or I missed a valid markup structure.

**Comment by andycwwai** [comment]
I found out that it is css of bootstrap's theme that causes the problem: it has a style "padding:8px" on ".table>tbody>tr>td". I've tried to change your css from ".responsive > tbody > tr > td" to ".table.responsive > tbody > tr > td" and it works. See if you have any other better idea to solve it. Once again, thank you for your great effort.

**Comment by awerlang** [comment]
Thanks for reporting. It is really a specificity problem, previously I had a dirty hack to deal with it. It is odd that on the examples page the problem doesn't show up. And I have a unit test that asserts that the `padding: 8px` is overriden with `50%`. Which version of bootstrap are you running on?

I can't use the class name `.table`, but I can repeat it like `.responsive.responsive`. CSS rules...

**Comment by andycwwai** [comment]
Thanks. FYI, we are using a theme "Spacelab" getting from http://bootswatch.com

**Comment by awerlang** [comment]
Checkout v0.4.1. Hope its fixed for good. If case not, please file a new issue. :)

**Comment by andycwwai** [comment]
It works perfect! Thanks.
