### ISSUE TITLE
"Error: th is null" when some TD's are mutually exclusive

### ISSUE THREAD

**Issue by fmunafo** [awerlang/angular-responsive-tables#16]
A very simple example to reproduce the error ("Error: th is null") in the console:

``` html
<!DOCTYPE html>
<html ng-app="test">
    <head>
        <!-- angular -->
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js"></script>
        <!-- angular responsive table -->
        <script src="https://cdn.rawgit.com/awerlang/angular-responsive-tables/master/release/angular-responsive-tables.min.js"></script>
        <link rel="stylesheet" href="https://cdn.rawgit.com/awerlang/angular-responsive-tables/master/release/angular-responsive-tables.min.css">
    </head>
    <body>
        <table data-wt-responsive-table>
            <thead>
                <tr>
                    <th>column</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td data-ng-if="true">tom</td>
                    <td data-ng-if="false">jerry</td>
                </tr>
            </tbody>
        </table>
        <script>angular.module("test", ['wt.responsive'])</script>
    </body>
</html>
```

Filippo

**Comment by awerlang** [comment]
Hello Filippo.

This is an interesting question. There's a somewhat limited support for dynamic columns, so let's avoid that.

As you said, at any point in time a single `td` would present data for a related `th`. But because the precise `td` might be different over time, a `th` title should be attached to all possible `td`. I have a overly simplistic process for it, consisting of a positional match. Although simple I believe it is good enough.

What about moving the condition inside the `td` element?

``` html
<tr>
    <td>{{true ? 'tom' : 'jerry'}}</td>
    <td>
        <component1 data-ng-if="true"></component1>
        <component2 data-ng-if="false"></component2>
    </td>
</tr>
```

**Comment by fmunafo** [comment]
Hi,
mine was a very simple example, just to show you how to reproduce it, but in the real world each `td` could have a lot of `html` elements inside it, and your suggestion isn't applicable anymore. Just think about having an anchor if the condition is true: it doesn't work anymore:

``` html
<td>{{true ? '<a href="https://github.com/awerlang/angular-responsive-tables">angular-responsive-tables</a>' : 'angular-responsive-tables'}}</td>
```

(maybe this code is syntactically wrong, but the following considerations do not change)

Try to do so with both conditions and with, for example, a nested list, and with 5-10 `td`....a nightmare :-(

I know, and appreciate, that the code of this directive is very small and easy, but I also think that this is something that needs improvement.

Anyway, thank you for the quick answer,
Filippo

**Comment by awerlang** [comment]
I believe it is a valid request. Otherwise it would require to enclose each condition in a container element (`div`).

To add this feature, support for dynamic columns, some sort of dynamic evaluation is required. This ideally should also solve #12. Perhaps a new directive would have to be applied on desired `td`'s. When required it would fetch the title from the corresponding `th` by position.

``` html
<table data-wt-responsive-table>
    <thead>
        <tr>
            <th>column</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td data-ng-if="true" data-wt-responsive-column>tom</td>
            <td data-ng-if="false" data-wt-responsive-column>jerry</td>
        </tr>
    </tbody>
</table>
```

**Comment by awerlang** [comment]
New attribute `responsive-dynamic` released in v0.2.0. 

plunker: https://embed.plnkr.co/Erhz8JePUVTrcKrmR2wr/

**Comment by fmunafo** [comment]
Hi,
thanks for fixing it.
I've just updated to v0.2.0 and the error has gone away but...I have not used the new directive (responsive-dynamic)! Have you removed the log or does it works also without directive?

Filippo

**Comment by awerlang** [comment]
I did quite a few things.
- I avoid the error, but it alone won't display the headers for multiple conditional columns;
- I added a feature to deal with one-time binding for ng-repeats, it is also able to deal with your scenario;
- But if you had a toggle to conditionally show/hide columns, _you'll need the `responsive-dynamic` attribute;_
- And as a last resort, there's the data-title attribute as per readme.

EDIT: the point in italics is handled by default beginning v0.3.0

**Comment by fmunafo** [comment]
Have a look at the following example, it does work without `responsive-dynamic`:

``` html
<table data-wt-responsive-table>
    <thead>
        <tr>
            <th>column 1</th>
            <th>column 2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>titty</td>
            <td data-title="column 2" data-ng-if="false">tom</td>
            <td data-title="column 2" data-ng-if="true">jerry</td>
        </tr>
    </tbody>
</table>
```

Maybe `data-title` has more "power" and it's enough to do the right job.

**Comment by awerlang** [comment]
> Maybe data-title has more "power" and it's enough to do the right job.

Exactly. Because it is explicit, it supercedes other, implicit alternatives.

**Comment by fmunafo** [comment]
In order to find a use case of `responsive-dynamic` that can be used without `data-title` I've found this strange behavior.

Rewrite your plunker: [https://embed.plnkr.co/Erhz8JePUVTrcKrmR2wr/](https://embed.plnkr.co/Erhz8JePUVTrcKrmR2wr/) like so:

``` html
<table data-wt-responsive-table>
    <thead>
        <tr>
            <th>columns</th>
            <th>simple</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td data-ng-if="false" responsive-dynamic>tom</td>
            <td data-ng-if="true" responsive-dynamic>jerry</td>
            <td>simple</td>
        </tr>
    </tbody>
</table>
```

It doesn't work anymore in responsive mode.

**Comment by awerlang** [comment]
I published a new version v0.2.1 that handles this scenario. Thanks for beta-testing!

Plunker updated: https://plnkr.co/edit/Erhz8JePUVTrcKrmR2wr?p=preview

Anyways, I had to employ a couple techniques that we'll better off without them for v0.2.2 or v0.3.0. It will make the codebase much simpler and cleaner.

**Comment by awerlang** [comment]
I removed `responsive-dynamic` in v0.3.0, scenarios with delayed loading/linking will work even without this attribute.

**Comment by fmunafo** [comment]
Great!
v.0.3.0 beta-test is ok :+1:
