### ISSUE TITLE
V0.3.0 Error "Controller 'wtResponsiveTable', required by directive 'td', can't be found!"

### ISSUE THREAD

**Issue by smxdevst** [awerlang/angular-responsive-tables#18]
New version giving this error (not minified version). Check if everything is included. If replacing with older version everything working good.

angular.js:13550 Error: [$compile:ctreq] Controller 'wtResponsiveTable', required by directive 'td', can't be found!

**Comment by awerlang** [comment]
I'm sorry to hear that, please let me know if that persists with the new release 0.3.1.

**Comment by Disane87** [comment]
it's fixed, thank you! :)

**Comment by Disane87** [comment]
it's fixed, thank you!
