### ISSUE TITLE
wt-responsive-table directive not working if under a container with ng-if

### ISSUE THREAD

**Issue by songokudbz** [awerlang/angular-responsive-tables#25]
If I have a nested table element in a div which contains **ng-if** directive the **wt-responsive-table** will not add the **responsive** class to the table. You have to add this manually. This happens because the variable that is used in the ng-if changes value in the controller from false to true and the wt-reponsive-table directive has already activated. Is there a solution to this? 
`<div ng-if=......>`
`<table wt-responsive-table>`
`....`
`</table>`
`</div>`
    <table wt-responsive-table>
        ....
    </table>

P.S. The problem if you add the **responsive** class manually is that you will not get the complete functionality from the directive, for example the title of the column will be empty.

**Comment by awerlang** [comment]
Hey! I have a fix for the `responsive` class, but I couldn't reproduce the issue about column's title. Can you provide a plunker?

**Comment by songokudbz** [comment]
It's hard for me to reproduce it now, but I've fixed it by adding responsive class to the table element and manually adding data-title to all the td's.

How to reproduce
1) create a variable in the controller: `$scope.test = true;`
2) go in the html write `<div ng-if="!test">` and inside add the `<table>` with the wt-responsive-table directive.
3) on controller init change `$scope.test = false` -> this should display the div element with the table element but the table element does not have the class="responsive" from the directive.
4) If this is not enough I will create a plunker later when I am not in the office.

Peace

**Comment by awerlang** [comment]
I released v0.4.4 which fixes the missing class issue. In this plunker you can verify adding the class is enough: https://plnkr.co/edit/ptSWYXZmRR4I7bQkzMT3?p=preview.

Please reopen if the problem persists.

**Comment by songokudbz** [comment]
It works. Thanks a million.
