### ISSUE TITLE
Allow th with ng-repeat over data from promise/remote

### ISSUE THREAD

**Issue by ADCJustinH** [awerlang/angular-responsive-tables#26]
Would be great if you could have dynamic headers with the dynamic content. Dynamic headers are especially useful for user defined content and this currently doesn't work due to timing I assume (th are not yet present when directive compiles...)

**Comment by ADCJustinH** [comment]
FYI I made this work for me by changing the compile function to a link function and watching the sum of the lengths of the th collection and the th textContents to know when the child elements were done rendering. After that you can kill the watcher.

**Comment by awerlang** [comment]
How is this different from #12 ? See a working plunker https://embed.plnkr.co/pSoSnRzf0gNMVsH5nFs4/

If this is a really separate issue, please send a plunker so we can work on it. Thanks!

**Comment by ADCJustinH** [comment]
It's related. I didn't search the closed issues :/ Basically If the columns are returned from a promise there is an issue. See: [https://plnkr.co/edit/ss37dNjcKFWGYrOaCJYe](https://plnkr.co/edit/ss37dNjcKFWGYrOaCJYe)

**Comment by awerlang** [comment]
I'd say it is enough to not show the table while column names are loading. An `ng-if` on the same element does the trick. WDYT?

Make sure you are using v0.4.4.
