### ISSUE TITLE
responsive-omit-title doesn't seem to work in v0.4.4

### ISSUE THREAD

**Issue by graspsolutions** [awerlang/angular-responsive-tables#27]

**Comment by awerlang** [comment]
Hey, thanks for reporting this!

Documentation doesn't cover its usage clearly. While `data-title` is an attribute, `responsive-omit-title` and `responsive-omit-if-empty` are classes. Usage:

```
<td class="responsive-omit-title">{{item.attribute}}</td>
```

**Comment by graspsolutions** [comment]
Ah, thank you for the clarification!
